#!/bin/sh

cd `dirname $0`

for file in *; do
    if [ $file = "awesome" ]; then
        file="config/$file"
    fi
    if [ $file = `basename $0` ]; then
	continue
    fi
    ln -vs "`pwd`/$file" "$HOME/.$file" > /dev/null 2> /dev/null

    if [ $? -eq 0 ]; then
        printf "\033[1;32m[SUCCESS]\033[m %s\n" $file
    else
        printf "\033[1;31m[FAILURE]\033[m %s\n" $file
    fi
done
