#!/bin/sh

cd `dirname $0`

for file in *; do
    dest_file=$file
    case "$file" in
    awesome|feh)
        dest_file="config/$file"
        ;;
    esac

    if [ $file = `basename $0` -o $file = "README" ]; then
	continue
    fi
    if [ -e "$HOME/.$dest_file" ]; then
        printf "\033[1;33m[ALREADY]\033[m %s\n" $file
	continue
    fi

    ln -vs "`pwd`/$file" "$HOME/.$dest_file" > /dev/null 2> /dev/null

    if [ $? -eq 0 ]; then
        printf "\033[1;32m[SUCCESS]\033[m %s\n" $file
    else
        printf "\033[1;31m[FAILURE]\033[m %s\n" $file
    fi
done
