#!/bin/bash

# Getting the config for rxvt
xrdb -merge ~/.Xresources

# Add a path
PATH="$HOME/.local/bin/:$PATH"
xdg-user-dirs-update

# Setting the screen dpi
xrandr --dpi 70

# Restoring the screen layouts if any is available
if [ -d "$HOME/.screenlayouts" ]; then
    for file in "$HOME/.screenlayouts/"*; do
        sh "$file"
    done
fi
